In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [3]:
a = Series([1,2,3],index = ['a','b','c'])
b = Series([4,5,6],index = ['d','c','e'])
a.index = ['x','y','z']
a.name = 'earn'
a.index.name = 'date'
print a

date
x    1
y    2
z    3
Name: earn, dtype: int64


In [68]:
s = Series([1,2,3],index = ['index1','index2','index3'])
#print s
data = {'a':s,
        'b':[4,5,6],
        'c':[7,8,9]}
a = DataFrame(data,columns = ['a','b','c','d'])
print a

        a  b  c    d
index1  1  4  7  NaN
index2  2  5  8  NaN
index3  3  6  9  NaN


In [ ]:
a = pd.Index(range(2,6))
print a
b = range(2,6)
print b, type(b)

In [ ]:
a = 8 if 0 else 2
print a

In [19]:
a = Series([1,2,3], ['a','b','c'])
a.name = 'value'
a.index.name = 'date'
b = DataFrame(a)
b.columns.name = 'name'
print b,type(b)

name  value
date       
a         1
b         2
c         3 <class 'pandas.core.frame.DataFrame'>


In [47]:
a = Series([1,2,3], ['a','b','c'])
b = a.reindex(['x','y','z'])
c = a.reindex(['a','c','d'], fill_value = 0)
print c

a    1
c    3
d    0
dtype: int64


In [225]:
a = DataFrame(np.arange(9).reshape(3,3), index = [1,2,3], columns = ['a','b','c'])
b = a.reindex([1,2,3,4], columns= ['a','b','c','d'])
print b
c = b.drop(['a','b'], axis = 1)
c = c.drop([1,2])
print c

d = c.dropna()
print d

     a    b    c   d
1  0.0  1.0  2.0 NaN
2  3.0  4.0  5.0 NaN
3  6.0  7.0  8.0 NaN
4  NaN  NaN  NaN NaN
     c   d
3  8.0 NaN
4  NaN NaN
Empty DataFrame
Columns: [c, d]
Index: []


In [262]:
a = DataFrame(np.arange(36).reshape(6,6),index = ['index1','index2','index3','index4','index5','index6'], columns = ['a','b','c','d','e','f'])
b = DataFrame(np.arange(9).reshape(3,3),index = ['index1','index2','index3'], columns = ['a','b','w'])
c = a[0:1]
print c,type(c)

        a  b  c  d  e  f
index1  0  1  2  3  4  5 <class 'pandas.core.frame.DataFrame'>


In [253]:
a = np.arange(16).reshape(4,4)
b = a[2,0:3]
print a,'\n'
print b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 8  9 10]


In [91]:
a = {'a':[1,2,3],
     'b':[4,5,6],
     'c':[7,8,9]}
b = DataFrame(a, columns = ['a','b','c'], index = ['x','y','z'])
c = b.reindex(index = ['x','a', 'y', 'z'], method = 'bfill', columns = ['a','b','c'])
print b,'\n'
print c

   a  b  c
x  1  4  7
y  2  5  8
z  3  6  9 

   a  b  c
x  1  4  7
a  1  4  7
y  2  5  8
z  3  6  9


In [141]:
a = DataFrame(np.arange(6).reshape(2,3),index = ['index1','index2'], columns = ['a','b','c'])
x = a['a']
b = a.add(x, axis = 0)
print a, '\n'
print b

        a  b  c
index1  0  1  2
index2  3  4  5 

        a  b  c
index1  0  1  2
index2  6  7  8


In [175]:
a = DataFrame(np.arange(9).reshape(3,3), index = list('abc'), columns = list('xyz'))
f = lambda x: x.max() - x.min()
b = a.apply(f, axis = 1)
print a, '\n'
print b

   x  y  z
a  0  1  2
b  3  4  5
c  6  7  8 

a    2
b    2
c    2
dtype: int64


In [180]:
a = DataFrame(np.arange(9).reshape(3,3), index = list('abc'), columns = list('xyz'))
def f(x):
    #return Series([x.max(), x.min()], index = ['max','min'])
    return x-2
b = a.applymap(f)
print a, '\n'
print b

   x  y  z
a  0  1  2
b  3  4  5
c  6  7  8 

   x  y  z
a -2 -1  0
b  1  2  3
c  4  5  6


In [185]:
a = DataFrame(np.arange(9).reshape(3,3), index = list('abc'), columns = list('xyz'))
b = np.floor(a)
print a, '\n'
print b

   x  y  z
a  0  1  2
b  3  4  5
c  6  7  8 

     x    y    z
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0


In [6]:
a = DataFrame(np.arange(9).reshape(3,3), index = list('cab'), columns = list('xzy'))
print a, '\n'
b = a.sort_values(by = 'x', ascending = False)
print b

   x  z  y
c  0  1  2
a  3  4  5
b  6  7  8 

   x  z  y
b  6  7  8
a  3  4  5
c  0  1  2


In [29]:
a = DataFrame({'a':[1,2,2,6,9,5],
               'b':[9,2,6,7,3,6],
               'c':[2,3,0,4,1,1]})
b = a.rank(axis = 0, method = 'max')
print a
print b

   a  b  c
0  1  9  2
1  2  2  3
2  2  6  0
3  6  7  4
4  9  3  1
5  5  6  1
     a    b    c
0  1.0  6.0  4.0
1  3.0  1.0  5.0
2  3.0  4.0  1.0
3  5.0  5.0  6.0
4  6.0  2.0  3.0
5  4.0  4.0  3.0


In [39]:
a = Series(np.arange(6), index = list('aabbcc'))
b = a.index.unique()
print a, '\n'
print b,type(b)
print a.index.is_unique

a    0
a    1
b    2
b    3
c    4
c    5
dtype: int32 

['a' 'b' 'c'] <type 'numpy.ndarray'>
False


In [105]:
a = DataFrame([[1, np.nan, 2],
               [6, 9, np.nan],
               [1, np.nan, 2],
               [6, 9, np.nan]],
               index = list('abcd'),
               columns = list('xyz'))
b = a.sum()
c = a.cumsum()
d = a.idxmax()
e = a.count()
f = a.min()
g = a.describe()
h = a.cumprod()
i = a.pct_change(axis = 1)
print a, '\n'
print i

   x    y    z
a  1  NaN  2.0
b  6  9.0  NaN
c  1  NaN  2.0
d  6  9.0  NaN 

    x    y    z
a NaN  NaN  1.0
b NaN  0.5  NaN
c NaN  NaN  1.0
d NaN  0.5  NaN


In [93]:
a = Series(list('aabc')*4)
print a

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object


In [147]:
a = {'a':1,'b':2}
b = {y:x for x,y in a.items()}
c = [y+1 for x,y in a.iteritems()]
print b

{1: 'a', 2: 'b'}


In [342]:
import tushare as ts
all_data = {}
for ticker in ['600380','601678','000962']:
    all_data[ticker] = ts.get_hist_data(ticker, '2015-01-01')
price = DataFrame({ticker:data['high'] for ticker, data in all_data.items()})
volume = DataFrame({ticker:data['volume'] for ticker, data in all_data.items()})
pct_change = price.pct_change()
pct_change = pct_change*100
idxmax = price.idxmax()
pricemax = price.ix[idxmax['600380']]['600380']
print idxmax, '\n'
print pricemax

000962    2015-06-05
600380    2015-05-22
601678    2015-04-08
dtype: object 

30.02


In [347]:
a = np.arange(9).reshape(3,3)
b = np.array([False,True,True])
c = a[b]
print a, '\n'
print c

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[3 4 5]
 [6 7 8]]


In [379]:
a = Series([1,6,8,2,6,1], index = [1,6,9,2,5,6])
b = a.value_counts()
c = a.unique()
d = np.sort(c)
print c, '\n'
print d

[1 6 8 2] 

[1 2 6 8]


In [375]:
a = np.array([1,6,8,2,6,0])
b = np.sort(a)
print a, '\n'
print b

[1 6 8 2 6 0] 

[0 1 2 6 6 8]


In [386]:
a = np.arange(9).reshape(3,3)
b = a[np.ix_([0,1],[1,2])]
print a, '\n'
print b

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1 2]
 [4 5]]


In [44]:
a = DataFrame(np.random.randint(9,size = 9).reshape(3,3), columns = ['a','b','c'])
b = [a[column].value_counts() for column in a.columns]
c = Series()
for s in b:
    #print s, '\n'
    if c.any():
        c = c.add(s, fill_value = 0)
    else:
        c = s
print a, '\n'
d = a.apply(pd.value_counts).fillna(0)
d['sum'] = d.sum(axis = 1)
print d

   a  b  c
0  0  7  1
1  1  8  0
2  6  2  6 

     a    b    c  sum
0  1.0  0.0  1.0  2.0
1  1.0  0.0  1.0  2.0
2  0.0  1.0  0.0  1.0
6  1.0  0.0  1.0  2.0
7  0.0  1.0  0.0  1.0
8  0.0  1.0  0.0  1.0


In [69]:
a = Series([1,2,3], index = ['a','b','c'])
b = Series([1,2,3], index = ['d','b','e'])
c = a + b
d = c.dropna()
print c, '\n'
print d

a    NaN
b    4.0
c    NaN
d    NaN
e    NaN
dtype: float64 

b    4.0
dtype: float64


In [10]:
a = np.random.randint(2,size = 9)
print a

[0 0 0 0 0 1 1 0 1]


In [62]:
from numpy import nan as NA
a = Series([1,NA])
b = a.dropna(axis = 0)
print a
print b

0    1.0
1    NaN
dtype: float64
0    1.0
dtype: float64


In [77]:
a = DataFrame(np.arange(9).reshape(3,3))
b = a.reindex(columns = [0,1,2,3])
c = b.dropna(axis = 1)
print b, '\n'
print c

   0  1  2   3
0  0  1  2 NaN
1  3  4  5 NaN
2  6  7  8 NaN 

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8


In [7]:
a = DataFrame(np.arange(9).reshape(3,3))
b = a[a.is()]
print a, '\n'
print b

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8 

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8
