In [1]:
import numpy as np
a = [1,2,3,4,5,6]
nd_a = np.array(a)
nd_a

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = [[1,2,3], [4,5,6]]
nd_b = np.array(b,float)
print type(nd_b)
print nd_b.dtype
print nd_b.shape

In [ ]:
c = [[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]]]
nd_c = np.array(c)
nd_c

In [ ]:
d = np.zeros((2,6))
print d

In [ ]:
e = np.ones((2,6))
print e

In [ ]:
f = np.empty((2,3))
print f

In [ ]:
g = np.arange(2,8)

In [ ]:
h = np.array(e)
print h
i = np.asarray(e)
print i

In [ ]:
j = np.ones_like(b, int)
print j

In [ ]:
k = np.eye(10)
print k

In [ ]:
l = np.identity(10)
l


In [ ]:
m = np.array([1,2,3],float)
n = np.array([1,2,3],dtype = np.int32)
print m.dtype
print n.dtype

In [ ]:
o = np.array([['1','2','3']],str)
print o.dtype
o_int = o.astype(int)
print o_int.dtype

print o
print o_int

In [ ]:
p = np.empty((5,6))
print type(p[2][2])

In [ ]:
q = np.arange(8)
q_slice = q[2:6]
print q
print q_slice

q_slice[2:] = 6
print q
print q_slice

In [ ]:
r = np.array([[1,2,3],[4,5,6],[7,8,9]])
r_slice = r[0:2].copy()
r_slice_slice = r_slice[1]
r_slice_slice[:] = 100
r_slice[1][1] = 2
print r
print r_slice
print r_slice_slice

In [ ]:
s = np.array([[1,2,3],[4,5,6],[7,8,9]])
print s
s[2,2] = 100
print s

In [ ]:
t = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
t_slice = t[1:, :2]
print t_slice

In [ ]:
name = np.array(['a','b','c'])
name_bool = name == 'a'
u = np.random.randn(3, 6)
print name_bool
print u
print '\n'

x = u < 0
print x
u[x] = 7
print u

In [ ]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,10,10],
             [11,11,11],
             [12,12,12]])
b = a[[1,5,2],[1,1,0]]
c = a[[1,5,2]]
d = c[1:3,[1,2,0]]
print c
print d
d[1,1:3] = 100
print d

In [ ]:
a = np.arange(20).reshape(4,5)
a.T

In [ ]:
a = np.array([9,2,3,4,0,6.2])
b = np.array([-2,2,7,8,0,-6])
print a
print b
print '\n'

c = a == 2
d = np.sqrt(a)
#d[np.isfinite(d)] = 100
print d

In [ ]:
% matplotlib inline
import matplotlib.pyplot as plt
a = np.arange(-5,5,0.01)
x,y =  np.meshgrid(a,a)
z = np.sqrt(x**2 + y**2)
plt.imshow(z, cmap = plt.cm.gray)
plt.colorbar()
plt.title('Image plot of $sqrt{x^2 + y^2}$ for a grid of values')

In [ ]:
a = np.array([1,5,9,3,6,8])
b = np.array([2,10,20,9,0,1])
c = np.array([True, False, False, True, False, True])
d = np.where(c, 2, 3)
print d
print np.array([(x if z else y) for x, y, z in zip(a,b,c)])

In [ ]:
a = np.random.randn(3,3)
np.where(a < 0, 2, a)


In [ ]:
a = np.array([[1,2,3],
             [9,10,6],
             [1,20,3]])
b = a.cumsum(1)
c = a.argmax()
print c

In [ ]:
a = np.random.randn(10)
#a.sort()
b = np.sort(a)
a.sort()
print a
print b
if (a == b).all():
    print 'yes'

In [ ]:
a = np.array(['a','f','c','d','e','c'])
print np.unique(a)

In [7]:
arr1 = np.arange(10)
arr2 = np.arange(16)
np.savez('file', aa = arr1, b = arr2)
np.save('file',arr1)

In [8]:
data = np.load('file.npy')
print data,type(data),'\n'

[0 1 2 3 4 5 6 7 8 9] <type 'numpy.ndarray'> 



In [4]:
data = np.load('file.npz')
a = data['aa']
b = data['b']
print data,type(data),'\n'
print a,type(a),'\n'
print b,type(b),'\n'

<numpy.lib.npyio.NpzFile object at 0x04AA3430> <class 'numpy.lib.npyio.NpzFile'> 

[0 1 2 3 4 5 6 7 8 9] <type 'numpy.ndarray'> 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] <type 'numpy.ndarray'> 



In [ ]:
from random import normalvariate
import random
n = 10
a = np.random.normal(size = n)
b = np.random.randn(n)
c = np.random.randint(1,100)
d = random.randn(1,2)
print d

In [ ]:
a = np.random.randn(19,2)
print a

In [ ]:
count = 20
draw = np.random.randint(0,2,size = count)
steps = np.where(draw > 0, 1, -1)
walk = np.cumsum(steps)

#print walk
print abs(walk)
print abs(walk) > 2
print (abs(walk) > 2).argmax()
for i in (abs(walk) > 2):
    if i == True:
        print i


In [ ]:
import numpy as ny
a = np.random.randint(1,10,size = 10)
print a


In [15]:
a = np.arange(81).reshape(9,9)
print a
print np.cumsum(a, axis = 1)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[  0   1   3   6  10  15  21  28  36]
 [  9  19  30  42  55  69  84 100 117]
 [ 18  37  57  78 100 123 147 172 198]
 [ 27  55  84 114 145 177 210 244 279]
 [ 36  73 111 150 190 231 273 316 360]
 [ 45  91 138 186 235 285 336 388 441]
 [ 54 109 165 222 280 339 399 460 522]
 [ 63 127 192 258 325 393 462 532 603]
 [ 72 145 219 294 370 447 525 604 684]]
